// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeInsure.Data;

#nullable disable

namespace WeInsure.Data.Migrations
{
    [DbContext(typeof(WeInsureDbContext))]
    [Migration("20260223212810_IntialDBSetup")]
    partial class IntialDBSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WeInsure.Domain.Entities.InsuredProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("InsuredProperties");
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Canceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PolicyType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.PolicyHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PolicyId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("PolicyId1");

                    b.ToTable("PolicyHolders");
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.InsuredProperty", b =>
                {
                    b.HasOne("WeInsure.Domain.Entities.Policy", null)
                        .WithOne("InsuredProperty")
                        .HasForeignKey("WeInsure.Domain.Entities.InsuredProperty", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WeInsure.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("InsuredPropertyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine3")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT");

                            b1.HasKey("InsuredPropertyId");

                            b1.ToTable("InsuredProperties");

                            b1.WithOwner()
                                .HasForeignKey("InsuredPropertyId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.Payment", b =>
                {
                    b.HasOne("WeInsure.Domain.Entities.Policy", null)
                        .WithOne("Payment")
                        .HasForeignKey("WeInsure.Domain.Entities.Payment", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WeInsure.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.Policy", b =>
                {
                    b.OwnsOne("WeInsure.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Price");

                            b1.HasKey("PolicyId");

                            b1.ToTable("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");
                        });

                    b.OwnsOne("WeInsure.Domain.ValueObjects.PolicyReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Reference");

                            b1.HasKey("PolicyId");

                            b1.ToTable("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.PolicyHolder", b =>
                {
                    b.HasOne("WeInsure.Domain.Entities.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeInsure.Domain.Entities.Policy", null)
                        .WithMany("PolicyHolders")
                        .HasForeignKey("PolicyId1");
                });

            modelBuilder.Entity("WeInsure.Domain.Entities.Policy", b =>
                {
                    b.Navigation("InsuredProperty")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("PolicyHolders");
                });
#pragma warning restore 612, 618
        }
    }
}
